name: flutter

on:
  workflow_dispatch:
  watch:
    types: started
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Install depot_tools
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git "$HOME/depot_tools"
        echo "$HOME/depot_tools" >> $GITHUB_PATH
    - name: make sysroot
      run: |
        mkdir sysroot
        TMP=$(mktemp -d)
        wget -c -P $TMP -i packages.txt
        find $TMP -name '*.deb' | xargs -I% dpkg -x % sysroot
        ln -s $(pwd)/sysroot/data/data/com.termux/files/* sysroot/
        echo "INPUT(-lc)" > sysroot/usr/lib/libpthread.so
        rm -r $TMP
    - name: checkout flutter
      run: |
        VERSION="3.29.0"
        git clone https://github.com/flutter/flutter -b $VERSION flutter
    - name: sync
      run: |
        sudo apt update
        sudo apt install libfreetype-dev ninja-build -y
        cp .gclient ./flutter/ && cd flutter && gclient sync
    - name: SSH
      uses: csexton/debugger-action@master
    
